"""Generate the two documents: index.html and examples/bench.html.

Both are built with the system they document, and both are divided the way the
guidelines board divides itself — a chapter label on the ground, and everything
under it inside a rounded container. Neither file is hand-edited.
"""
import html, pathlib
from parts import (ROOT, THEME_JS, head, chapter, container, block, rail, frame,
                   controls_section, fields_section, surfaces_section,
                   loading_section, look_section, ground_section,
                   type_section, colour_section)

# generated by src/paste.py from src/parts.py, and asserted against core.css by
# src/doc.py — never hand-written, because this is the one document a model
# actually reads
PASTE = html.escape((ROOT / "src/paste.txt").read_text())

FOOT = ('  <div class="rayl-container">\n'
        '    <span class="rayl-label">Azeret and Concrette are TRIAL cuts — '
        'licence them before anything public</span>\n'
        '  </div>\n')

TAIL = "\n</div>\n" + THEME_JS + "\n</body>\n</html>\n"


# ----------------------------------------------------------- the page --------
# "A page" was hand-written, so it went on demonstrating the system as it stood
# on the day somebody typed it. It is generated now: a rule change reaches it on
# the next build, and a component that ships without appearing here is a
# component nothing composes.

LANDING = (ROOT / "src/landing.html").read_text()

landing = (
  '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
  '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
  '<title>Rayl Landing</title>\n'
  '<script src="https://typograaf.github.io/rayl-system/rayl.js"></script>\n'
  '<script type="module" src="https://typograaf.github.io/rayl-system/assets/array/rayl-array.js"></script>\n'
  '</head>\n<body class="rayl">\n' + LANDING + "\n" + THEME_JS + "\n</body>\n</html>\n"
)
(ROOT / "examples/landing.html").write_text(landing)
print("examples/landing.html", len(landing), "bytes")


# ------------------------------------------------------------- the bench ----
# An overview, not an explanation. Every part the system ships, shown at the
# size it ships at, with nothing between the label and the thing itself.

bench = (
    head("Rayl Control Bench", "https://typograaf.github.io/rayl-system/rayl.js")
    + controls_section()
    + fields_section()
    + surfaces_section()
    + loading_section()
    + look_section()
    + ground_section()
    + type_section()
    + colour_section()
    + FOOT + TAIL
)
(ROOT / "examples/bench.html").write_text(bench)
print("examples/bench.html", len(bench), "bytes")


# --------------------------------------------------------- the dashboard ----
# The one page somebody who has never read code lands on. It keeps its opening
# copy, because telling them what to do with the block is its entire job.

PASTE_CSS = """
  pre{margin:0;font:inherit;font-size:12px;line-height:1.5;white-space:pre-wrap;
    word-break:break-word;}
"""

LINKS = chapter("Where everything is") + block(
    rail("Everything else",
         "The examples show the parts composed. Build the structure your brief "
         "needs — cloning one gives you a page shaped like somebody else\u2019s problem."),
    frame("The examples",
          '<div class="rayl-cluster">'
          '<a class="rayl-btn" href="examples/landing.html">A page</a>'
          '<a class="rayl-btn" href="examples/panel.html">A panel</a>'
          '<a class="rayl-btn" href="examples/bench.html">The bench</a>'
          '<a class="rayl-btn" href="examples/array.html">The array</a></div>'),
    frame("The documents",
          '<div class="rayl-cluster">'
          '<a class="rayl-btn" href="RAYL-RULES.md">The rules</a>'
          '<a class="rayl-btn" href="RAYL-WHY.md">Why</a>'
          '<a class="rayl-btn" href="RAYL-OPEN.md">What is open</a></div>'),
    frame("The files",
          '<div class="rayl-cluster">'
          '<a class="rayl-btn" href="rayl.js">rayl.js</a>'
          '<a class="rayl-btn" href="rayl-vars.css">rayl-vars.css</a>'
          '<a class="rayl-btn" href="rayl.tokens.json">tokens.json</a>'
          '<a class="rayl-btn" href="rayl-check.py">rayl-check.py</a>'
          '<a class="rayl-btn" href="assets/logo/Lockup.svg">Lockup</a></div>'),
)

HERO = ('  <div class="rayl-container">\n'
        '    <div class="rayl-split is-lead is-centred">\n'
        '      <div class="rayl-stack">\n'
        '        <span class="rayl-label">The Rayl design system</span>\n'
        '        <h1 class="rayl-48">Hand this to an AI and what it builds comes '
        'out looking like Rayl.</h1>\n'
        '      </div>\n'
        '      <div class="rayl-stack">\n'
        '        <p class="rayl-18">Including the parts nobody has designed yet. '
        'You do not need to read any code to use it — copy the block below and '
        'paste it above whatever you are asking for.</p>\n'
        '        <div class="rayl-cluster">\n'
        '          <a class="rayl-btn" href="#the-block">The block</a>\n'
        '          <a class="rayl-btn" href="RAYL-RULES.md">The rules</a>\n'
        '          <a class="rayl-btn" href="examples/bench.html">The bench</a>\n'
        '        </div>\n'
        '      </div>\n'
        '    </div>\n'
        '  </div>\n')

PASTE_BLOCK = chapter("The block", "the-block") + block(
    rail("Paste this at the top of your prompt",
         "It carries the tokens, the type scale, the layout primitives and every "
         "control. You do not need to read any of it.",
         "It also tells the model what the system does NOT have, what to do when "
         "it hits one of those, and how to check its own work before it answers.")
    + '<div class="rayl-rail-foot rayl-stack rayl-gap-12">'
      '<button class="rayl-ibtn" data-icon="Document" id="copy">Copy the block</button>'
      '<span class="rayl-label">Generated from src/parts.py</span></div>',
    # the pre sat in a box inside a frame — two containers doing one job
    frame(None, f'<pre id="paste">{PASTE}</pre>'))

COPY_JS = '''<script>
  document.getElementById("copy").addEventListener("click",function(){
    navigator.clipboard.writeText(document.getElementById("paste").textContent);
  });
</script>'''

index = (
    head("Rayl System", "rayl.js", PASTE_CSS)
    + HERO
    + PASTE_BLOCK
    + type_section()
    + colour_section()
    + LINKS
    + FOOT
    + "\n</div>\n" + THEME_JS + "\n" + COPY_JS + "\n</body>\n</html>\n"
)
(ROOT / "index.html").write_text(index)
print("index.html", len(index), "bytes")
