"""Generate the two documents: index.html and examples/bench.html.

Both are built with the system they document, and both are divided the way the
guidelines board divides itself — a chapter label on the ground, and everything
under it inside a rounded container. Neither file is hand-edited.
"""
import html, pathlib
from parts import (ROOT, THEME_JS, head, chapter, container, block, rail, frame,
                   controls_section, fields_section, surfaces_section,
                   loading_section, look_section, ground_section,
                   type_section, colour_section)

# generated by src/paste.py from src/parts.py, and asserted against core.css by
# src/doc.py — never hand-written, because this is the one document a model
# actually reads
PASTE = html.escape((ROOT / "src/paste.txt").read_text())

FOOT = ('  <div class="rayl-container">\n'
        '    <span class="rayl-label">Azeret and Concrette are TRIAL cuts — '
        'licence them before anything public</span>\n'
        '  </div>\n')

TAIL = "\n</div>\n" + THEME_JS + "\n</body>\n</html>\n"


# ----------------------------------------------------------- the page --------
# "A page" was hand-written, so it went on demonstrating the system as it stood
# on the day somebody typed it. It is generated now: a rule change reaches it on
# the next build, and a component that ships without appearing here is a
# component nothing composes.

LANDING = (ROOT / "src/landing.html").read_text()

landing = (
  '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
  '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
  '<title>Rayl Landing</title>\n'
  '<script src="https://typograaf.github.io/rayl-system/rayl.js"></script>\n'
  '<script type="module" src="https://typograaf.github.io/rayl-system/assets/array/rayl-array.js"></script>\n'
  '</head>\n<body class="rayl">\n' + LANDING + "\n" + THEME_JS + "\n</body>\n</html>\n"
)
(ROOT / "examples/landing.html").write_text(landing)
print("examples/landing.html", len(landing), "bytes")


# ------------------------------------------------------------- the bench ----
# An overview, not an explanation. Every part the system ships, shown at the
# size it ships at, with nothing between the label and the thing itself.

bench = (
    head("Rayl Control Bench", "https://typograaf.github.io/rayl-system/rayl.js")
    + controls_section()
    + fields_section()
    + surfaces_section()
    + loading_section()
    + look_section()
    + ground_section()
    + type_section()
    + colour_section()
    + FOOT + TAIL
)
(ROOT / "examples/bench.html").write_text(bench)
print("examples/bench.html", len(bench), "bytes")


# --------------------------------------------------------- the dashboard ----
# The one page somebody who has never read code lands on. It keeps its opening
# copy, because telling them what to do with the block is its entire job.

PASTE_CSS = """
  pre{margin:0;font:inherit;font-size:12px;line-height:1.4;white-space:pre-wrap;
    word-break:break-word;}
"""

# ---------------------------------------------------------------------------
# The dashboard had two jobs and did neither. It dumped nine thousand
# characters of block into the page — text whose only purpose is to be COPIED,
# which nobody reads and which buried everything under it — and then repeated
# the type scale and the whole palette, both of which the bench already lays
# out properly. A page cannot be the specimen sheet and the front door at once.
#
# It is the front door. One statement, the button that does the only thing this
# page is for, and the four places to go. The block is still here and still
# readable, behind a fold, because somebody wanting to check what they are
# about to paste should be able to — not because it needs to be on screen.

HERO = ('  <div class="rayl-container">\n'
        '    <div class="rayl-split is-lead is-centred">\n'
        '      <div class="rayl-stack">\n'
        '        <span class="rayl-label">The Rayl design system</span>\n'
        '        <h1 class="rayl-48">Hand this to an AI and what it builds comes '
        'out looking like Rayl.</h1>\n'
        '      </div>\n'
        '      <div class="rayl-stack">\n'
        '        <p class="rayl-18">Including the parts nobody has designed yet. '
        'Copy the block, paste it above whatever you are asking for. You do not '
        'need to read any of it, or any code.</p>\n'
        '        <div class="rayl-cluster">\n'
        '          <button class="rayl-ibtn" data-icon="Document" id="copy">Copy the block</button>\n'
        '          <a class="rayl-btn" href="RAYL-RULES.md">The rules</a>\n'
        '          <a class="rayl-btn" href="examples/bench.html">The bench</a>\n'
        '        </div>\n'
        '      </div>\n'
        '    </div>\n'
        '  </div>\n')

# The block itself is not on the page. Its only job is to reach a clipboard,
# and a reader deciding whether to paste it wants the hero's sentence, not nine
# thousand characters. It lives here as the copy button's source and nothing
# else; src/paste.txt is the same bytes at a URL for anybody who wants to read
# them.
PASTE_SOURCE = f'  <pre id="paste" hidden>{PASTE}</pre>\n'

COPY_JS = '''<script>
  /* The button is in the hero and the text is in the fold, so the copy does not
     depend on the fold being open — which is the whole point of folding it. */
  document.getElementById("copy").addEventListener("click",function(){
    navigator.clipboard.writeText(document.getElementById("paste").textContent);
  });
</script>'''


LINKS = chapter("Where everything is") + block(
    rail("Everything else",
         "The bench is the specimen sheet: every control, the type scale, the "
         "palette and the tokens, at the size they ship at.",
         "The examples show the parts composed. Build the structure your brief "
         "needs \u2014 cloning one gives you a page shaped like somebody else\u2019s "
         "problem."),
    frame(None,
          '<div class="rayl-stack rayl-gap-12">'
          '<span class="rayl-label">The examples</span>'
          '<div class="rayl-cluster">'
          '<a class="rayl-btn" href="examples/bench.html">The bench</a>'
          '<a class="rayl-btn" href="examples/landing.html">A page</a>'
          '<a class="rayl-btn" href="examples/panel.html">A panel</a>'
          '<a class="rayl-btn" href="examples/array.html">The array</a>'
          '<a class="rayl-btn" href="examples/look.html">The look</a></div>'
          '<span class="rayl-label">The documents</span>'
          '<div class="rayl-cluster">'
          '<a class="rayl-btn" href="RAYL-RULES.md">The rules</a>'
          '<a class="rayl-btn" href="RAYL-WHY.md">Why</a>'
          '<a class="rayl-btn" href="RAYL-OPEN.md">What is open</a></div>'
          '<span class="rayl-label">The files</span>'
          '<div class="rayl-cluster">'
          '<a class="rayl-btn" href="rayl.js">rayl.js</a>'
          '<a class="rayl-btn" href="rayl-vars.css">rayl-vars.css</a>'
          '<a class="rayl-btn" href="rayl.tokens.json">tokens.json</a>'
          '<a class="rayl-btn" href="rayl-check.py">rayl-check.py</a>'
          '<a class="rayl-btn" href="src/paste.txt">The block, as text</a>'
          '<a class="rayl-btn" href="assets/logo/Lockup.svg">Lockup</a></div>'
          '</div>'))


index = (
    head("Rayl System", "rayl.js", PASTE_CSS)
    + HERO
    + LINKS
    + FOOT
    + PASTE_SOURCE
    + "\n</div>\n" + THEME_JS + "\n" + COPY_JS + "\n</body>\n</html>\n"
)
(ROOT / "index.html").write_text(index)
print("index.html", len(index), "bytes")
